USE DVLD;

GO 

INSERT INTO Persons (FirstName,LastName,NationalityCountryID,Address,DateOfBirth,Gender,Email,NationalNumber,PhoneNumber)
VALUES
('Ammar','Albaghajati',170, 'Damascus 123 street', 22-09-2004,'M','ammaralbaghajati@gmail.com','123',05348406276);

INSERT INTO Users (PersonID, Username, Password, IsActive, Permissions)
VALUES
(1,'ammar','198086',1,0);

INSERT INTO Services (ServiceName, ServiceFee)
VALUES 
('First-time driving license issuance',15),
('Retake test',5),
('Driving license renewal',5),
('Replacement of lost license',10),
('Replacement of damaged license',5),
('Release of detained license',15),
('International driving license issuance',50);

INSERT INTO TestTypes (TestTypeName, TestTypeDescription, TestFee)
VALUES
('Vision Test','This assesses the applicant''s visual acuity to ensure they have sufficient vision to drive safely.',10),
('Theoretical Test','This test assesses the applicant''s knowledge of traffic rules, road signs, and driving regulations. It typically consists of multiple-choice questions, and the applicant must select the correct answer(s). The written test aims to ensure that the applicant understands the rules of the road and can apply them in various driving scenarios.',20),
('Practical Driving Test','This test evaluates the applicant''s driving skills and ability to operate a motor vehicle safely on public roads. A licensed examiner accompanies the applicant in the vehicle and observes their driving performance.',30);

INSERT INTO ApplicationStatuses (StatusName)
VALUES 
('New'),
('Canceled'),
('Completed');

INSERT INTO LicenseTypes (TypeName)
VALUES 
('New'),
('Renewal'),
('Replacement Lost'),
('Replacement Damaged');

INSERT INTO LicenseClasses (ClassName, ClassDescription, ValidityLengthInYears, MinimumAllowedAge, ClassFees)
VALUES 
('Class 1 – Small Motorcycle License','Allows driving small motorcycles.',5,18,15),
('Class 2 – Heavy Motorcycle License','Allows driving heavy and powerful motorcycles',5,21,30),
('Class 3 – Regular Driving License','Allows driving light vehicles and personal cars',10,18,20),
('Class 4 – Commercial Driving License','Allows driving taxis and limousines.',10,21,200),
('Class 5 – Agricultural Vehicles License','Allows driving all agricultural vehicles (Tractors, etc.).',10,21,50),
('Class 6 – Small and Medium Bus License','Allows driving small and medium buses.',10,21,250),
('Class 7 – Trucks and Heavy Vehicles License','Allows driving trucks and heavy vehicles (buses, large trucks).',10,21,300);

INSERT INTO Countries (CountryName)
VALUES
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo (Congo-Brazzaville)'),
('Costa Rica'),
('Côte d''Ivoire'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czechia (Czech Republic)'),
('Democratic Republic of the Congo'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Eswatini (formerly Swaziland)'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Grenada'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Israel'),
('Italy'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar (formerly Burma)'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('North Korea'),
('North Macedonia (formerly Macedonia)'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Palestine State'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Korea'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States of America'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe');
